# Generated by Django 2.0.3 on 2018-04-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_order_fav_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fav_type',
            new_name='ctype',
        ),
    ]
