# Generated by Django 2.0.3 on 2018-04-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180405_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '公户'), (2, '私户'), (3, '已处理')], default=1),
        ),
    ]
