# Generated by Django 2.0.3 on 2018-04-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180408_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='content',
            new_name='aa',
        ),
        migrations.AddField(
            model_name='update',
            name='detail',
            field=models.TextField(default='3137990404', verbose_name='详细'),
            preserve_default=False,
        ),
    ]
