# Generated by Django 2.0.3 on 2018-04-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_update_bb'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='ptime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
